---
name: Rust

on:
  push:
    branches: ["main, return_task"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --bin lamella-client --verbose
    - name: Run tests
      run: cargo test lamella-client --verbose

  build-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --bin lamella-server --verbose
    - name: Run tests
      run: cargo test lamella-server --verbose
